### ISSUE TITLE
Variable declaration 

### ISSUE THREAD

**Issue by ghassanmas** [srish/Scrape-Soup-Send#1]
Hello there. You have defined a variable as "message", then you pass it to function  "sendMsg" as "msg".

https://github.com/srish/Scrape-Soup-Send/blob/ba1ac4deaf1a8762ad3a3a2f4f281fabca131c7d/scrape_and_soup_and_send.py#L48-L49

**Comment by srish** [comment]
@ghassanmas thanks for reporting this issue! I've pushed a fix for this :)
